url: https://santteegt.github.io
baseurl: /aigentslab/

# Site settings
title: AIgents Lab
email: hernangt12re3@gmail.com
description: "Tecnologías de Analítica de datos y Computación Cognitiva que brindan un servicio democratizado de toma de decisiones sin costos de implementación"


# Team names, titles and social links
people:
- name: Santiago Gonzalez
  pic: 1
  position: MSc Eng. Data Science Engineer, Full Stack Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Andres Barnuevo
  pic: 2
  position: MSc Eng. Experto en Seguridad, Desarrollador de Software
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Oscar Malgiaritta
  pic: 3
  position: Eng. Full Stack Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: #
  - title: facebook
    url:
  - title: stack-overflow
    url: #
  - title: bitbucket
    url: #
  - title: github
    url: #

# Postal address (add as many lines as necessary)
address:
  - line: Cuenca, Ecuador

# Build settings
markdown: kramdown
permalink: pretty
