url: https://santteegt.github.io
baseurl: /aigentslab/

# Site settings
title: AIgents Lab
email: hernangt12re3@gmail.com
description: "Tecnologías de Analítica de datos y Computación Cognitiva que brindan un servicio democratizado de toma de decisiones sin costos de implementación"


# Team names, titles and social links
people:
- name: Andres Barnuevo
  pic: 1
  position: MSc Seguridad de la Informacion
  area: Consultor Senior y Desarrollador de Software
  role: Co-Fundador
  social:
    - title: twitter
      url: https://twitter.com/andresbarnuevo
    - title: linkedin
      url: https://www.linkedin.com/in/andresbarnuevo/
    - title: github
      url: #

- name: Santiago Gonzalez
  pic: 2
  position: MSc Web Science and Big Data Analytics
  area: Data Science Engineer & Full Stack Developer
  role: Co-Fundador
  social:
    - title: twitter
      url: https://twitter.com/santteegt
    - title: linkedin
      url: https://www.linkedin.com/in/santteegt/
    - title: github
      url: https://santteegt.github.io/

- name: Oscar Malgiaritta
  pic: 3
  position: Ingeniero de Sistemas
  area: Freelance Full Stack Developer
  role: Co-Fundador
  social:
    - title: twitter
      url: https://twitter.com/omalgia
    - title: linkedin
      url: https://www.linkedin.com/in/oscar-malgiaritta-53a7978b/
    - title: github
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: #
  - title: facebook
    url:
  - title: stack-overflow
    url: #
  - title: bitbucket
    url: #
  - title: github
    url: #

# Postal address (add as many lines as necessary)
address:
  - line: Cuenca, Ecuador

# Build settings
markdown: kramdown
permalink: pretty
